
name: Build and Deploy DirectoryListing to IIS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '4.0.x'

    - name: Restore dependencies
      run: dotnet restore DirectoryListing.sln

    - name: Build solution
      run: dotnet build DirectoryListing.sln --configuration Release

    - name: Publish project
      run: dotnet publish DirectoryListing.sln -c Release -o C:\inetpub\wwwroot\DirectoryListing
